# SPDX-License-Identifier: GPL-2.0

# NOTE: link order is important
obj-$(CONFIG_PORTMUX)		+= portmux-core.o
obj-$(CONFIG_PORTMUX_GPIO)	+= portmux-gpio.o
obj-$(CONFIG_PORTMUX_DUMMY)	+= portmux-dummy.o portmux-testing.o
