# SPDX-License-Identifier: GPL-2.0
#
# Combined port bus drivers
#
# Copyright (C) 2020 Enrico Weigelt, metux IT consult <info@metux.net>
#
obj-$(CONFIG_COMBOPORT) += comboport-core.o
obj-$(CONFIG_COMBOPORT_DUMMY) += comboport-dummy.o
obj-$(CONFIG_COMBOPORT_GENERIC) += comboport-generic.o
